name: Deploy Individual Backends

on:
  push:
    branches: [master]
    paths:
      - "pybackend/**"
  workflow_dispatch:
    inputs:
      server_type:
        description: "Server type"
        required: true
        default: "uvicorn"
        type: choice
        options:
          - uvicorn
          - daphne
      use_ssl:
        description: "Use SSL"
        required: false
        default: false
        type: boolean
      skip_migrations:
        description: "Skip migrations"
        required: false
        default: false
        type: boolean

jobs:
  deploy-python-backend:
    name: Deploy Python Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to Azure VM and deploy Python backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          script: |
            echo "Connected to Azure VM. Starting Python backend deployment process..."

            # Đi đến thư mục chứa repository
            cd ${{ secrets.PROJECT_PATH }}

            # Pull code mới từ GitHub
            git pull

            # Đi đến thư mục pybackend
            cd ${{ secrets.PROJECT_PATH }}/pybackend

            # Cài đặt dependencies nếu có thay đổi trong requirements.txt
            if git diff --name-only HEAD^ HEAD | grep -q "pybackend/requirements.txt"; then
              echo "Installing Python dependencies..."
              pip install -r requirements.txt
            fi

            # Xác định các tham số cho restart command
            SERVER_TYPE="${{ github.event.inputs.server_type || 'uvicorn' }}"
            SSL_FLAG="${{ github.event.inputs.use_ssl == 'true' && '--ssl' || '' }}"
            MIGRATIONS_FLAG="${{ github.event.inputs.skip_migrations == 'true' && '--skip-migrations' || '' }}"

            # Restart Python backend
            echo "Restarting Python backend with server type: $SERVER_TYPE"
            python run_azure_server.py --action restart --server $SERVER_TYPE $SSL_FLAG $MIGRATIONS_FLAG

            echo "Python backend deployed successfully."
