name: Deploy Individual Backends

on:
  push:
    branches: [master]
    paths:
      - "pybackend/**"
  workflow_dispatch:
    inputs:
      server_type:
        description: "Server type"
        required: true
        default: "uvicorn"
        type: choice
        options:
          - uvicorn
          - daphne
      use_ssl:
        description: "Use SSL"
        required: false
        default: false
        type: boolean
      skip_migrations:
        description: "Skip migrations"
        required: false
        default: false
        type: boolean

jobs:
  deploy-python-backend:
    name: Deploy Python Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to Azure VM and deploy Python backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          script: |
            echo "Connected to Azure VM. Starting Python backend deployment process..."

            cd ${{ secrets.PROJECT_PATH }}
            git pull
            cd pybackend

            # Kích hoạt virtualenv nếu có
            if [ -d "venv" ]; then
              source venv/bin/activate
            fi

            cd fashion_backend/backend

            # Tạo hoặc attach vào tmux session tên runserver
            if ! tmux has-session -t runserver 2>/dev/null; then
              tmux new-session -d -s runserver
            fi

            # Chạy lệnh trong tmux session
            tmux send-keys -t runserver "python manage.py runserver 0.0.0.0:8000" C-m

            echo "Python backend started in tmux session 'runserver'."
