name: Deploy to Azure VM

on:
  workflow_dispatch:
    inputs:
      deploy_python:
        description: "Deploy Python backend"
        required: true
        default: true
        type: boolean
      deploy_node:
        description: "Deploy Node.js payment backend"
        required: true
        default: true
        type: boolean

jobs:
  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest code from GitHub
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull

      - name: Deploy Python backend - Install dependencies
        if: ${{ github.event.inputs.deploy_python == 'true' }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}/pybackend
            if git diff --name-only HEAD^ HEAD | grep -q "pybackend/requirements.txt"; then
              echo "Installing Python dependencies..."
              pip install -r requirements.txt
            fi

      - name: Deploy Python backend - Restart server
        if: ${{ github.event.inputs.deploy_python == 'true' }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}/pybackend
            echo "Restarting Python backend..."
            python run_azure_server.py --action restart --server uvicorn
            echo "Python backend deployed successfully."

      - name: Deploy Node.js payment backend - Install dependencies
        if: ${{ github.event.inputs.deploy_node == 'true' }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}/fashion_payment
            if git diff --name-only HEAD^ HEAD | grep -q "fashion_payment/package.json"; then
              echo "Installing Node.js dependencies..."
              npm install
            fi

      - name: Deploy Node.js payment backend - Restart server
        if: ${{ github.event.inputs.deploy_node == 'true' }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}/fashion_payment
            echo "Restarting Node.js payment backend..."
            node run_azure_server.js restart
            echo "Node.js payment backend deployed successfully."
